env:
  global:
    - CC_TEST_REPORTER_ID=7b41a0ba8eb70ee1fcc480226e74747da8d200931e72ab25404c3b6dd96ff24b
language: node_js
node_js:
  - "stable"
before_script:
  node_js:
  - "stable"
script:
    - npm test
    - npm run coverage
after_success: 'npm run coveralls'